CREATE TABLE RECORD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    COST INT NOT NULL,
    TOTAL_STOCK INT NOT NULL,
    OWNED INT NOT NULL
);
